from __future__ import annotations

from enum import StrEnum


class QuoteMode(StrEnum):
    EXECUTABLE = "EXECUTABLE"
    INDICATIVE_ONLY = "INDICATIVE_ONLY"


class TradeClassification(StrEnum):
    TRUE_ARBITRAGE = "TRUE_ARBITRAGE"
    NEAR_ARBITRAGE = "NEAR_ARBITRAGE_WITH_SMALL_BASIS_RISK"
    RELATIVE_VALUE = "RELATIVE_VALUE_TRADE"
    NO_TRADE = "NO_TRADE"


class ObservationKind(StrEnum):
    RECORDED = "RECORDED_HISTORICAL"
    SYNTHETIC = "SYNTHETIC_EXAMPLE"
    RECONSTRUCTED = "RECONSTRUCTED"
    LIVE_INDICATIVE = "CURRENT_LIVE_INDICATIVE"
    USER_SUPPLIED = "HISTORICAL_USER_SUPPLIED_FIXTURE"
    MANUAL = "MANUAL_USER_SUPPLIED"


class RiskFlag(StrEnum):
    FUTURES_SPREAD = "FUTURES_BID_ASK_SPREAD"
    KALSHI_SPREAD = "KALSHI_BID_ASK_SPREAD"
    TRANSACTION_COSTS = "TRANSACTION_COSTS"
    STALE_QUOTE = "STALE_QUOTE"
    UNSYNCHRONIZED_QUOTES = "UNSYNCHRONIZED_QUOTES"
    INDICATIVE_ONLY = "INDICATIVE_ONLY"
    CROSSED_MARKET = "CROSSED_MARKET"
    COARSE_PRECISION = "COARSE_QUOTE_PRECISION"
    MARKET_CLOSED = "MARKET_CLOSED"
    MISSING_BOOK_SIDE = "MISSING_BOOK_SIDE"
    INSUFFICIENT_DEPTH = "INSUFFICIENT_DEPTH"
    PARTIAL_FILL = "PARTIAL_FILL_RISK"
    POSITION_LIMIT = "POSITION_LIMIT"
    CAPITAL_LIMIT = "CAPITAL_LIMIT"
    INTEGER_HEDGE = "INTEGER_HEDGE_RESIDUAL"
    BASIS_RISK = "EFFR_TARGET_BASIS_RISK"
    SETTLEMENT_MISMATCH = "SETTLEMENT_DEFINITION_MISMATCH"
    TAIL_RISK = "UNMODELED_OR_TAIL_OUTCOME_RISK"
    MULTIPLE_MEETINGS = "MULTIPLE_MEETINGS_IN_CURVE"
    MODEL_UNDERIDENTIFIED = "MODEL_UNDERIDENTIFIED"
    QUOTE_ROUNDING = "QUOTE_ROUNDING"
    ASYNC_EXECUTION = "CANNOT_EXECUTE_VENUES_ATOMICALLY"
    HOLIDAY_CARRY = "WEEKEND_OR_HOLIDAY_RATE_CARRY"
